language: python
python:
  - "2.7"
before_install:
  # Setup virtual framebuffer
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Setup mutter WM
  - sudo apt-get --fix-missing install mutter
  - dbus-launch mutter &
  - sleep 3
install:
  # Install AcTor dependencies
  - sudo apt-get --fix-missing install python-gi python-gobject python-dbus python-wnck libwnck-3-0
  - pip install -r requirements.txt
  # Install Hamster time tracker
  - sudo add-apt-repository ppa:dylanmccall/hamster-time-tracker-git-stable -y
  - sudo apt-get update
  # Install TaskWarrior
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake uuid-dev g++-4.8
  - git clone https://git.tasktools.org/scm/tm/task.git
  - pushd task
  - git checkout v2.4.1
  - git clean -dfx
  - cmake .
  - make
  - sudo make install
  - popd
  - rm -rf task
  # Install testing dependencies
  - sudo apt-get --fix-missing install hamster-time-tracker gedit gcalctool xdotool
  - pip install coveralls
  - pip install pytest pytest-cov
  # Give the window manager some exercise
  - gedit &
  - for window in `xdotool search --name gedit`; do xdotool windowactivate $window || :; done
  - sleep 1
  - for window in `xdotool search --name gedit`; do xdotool windowkill $window || :; done
  - sleep 1
virtualenv:
    system_site_packages: true
script:
  - py.test --cov . --cov-report term-missing
after_script:
  - coveralls
